### ISSUE TITLE
be careful with your credentials  try to use ENV vars to do that

### ISSUE THREAD

**Issue by Freivincampbell** [codesprintpro/urlshortner#1]
https://github.com/codesprintpro/urlshortner/blob/c3de25cf9060400c17050df09ef3f3c6888d0470/config/default.json#L2

**Comment by codesprintpro** [comment]
Hey Freivincampbell thanks for noting it...I have deleted that user from mongodb

**Comment by Freivincampbell** [comment]
it is nothing, you are very welcome.
